name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.runner }} ${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: ubuntu
            ext: ''
          - runner: windows-latest
            target: windows_x86_64
            ext: '.exe'
          - runner: macos-latest
            target: macos_arm64
            ext: ''
          - runner: macos-15-intel
            target: macos_x86_64
            ext: ''
    steps:
      - uses: actions/checkout@v6
      - name: Build release
        run: cargo build --release

      - name: Rename binary (Unix)
        if: matrix.runner != 'windows-latest'
        run: mv target/release/chip8 target/release/chip8-${{ matrix.target }}

      - name: Rename binary (Windows)
        if: matrix.runner == 'windows-latest'
        shell: bash
        run: mv target/release/chip8.exe target/release/chip8-${{ matrix.target }}${{ matrix.ext }}

      - name: Attach files to GitHub Release
        uses: softprops/action-gh-release@v2s
        with:
          files: target/release/chip8-${{ matrix.target }}${{ matrix.ext }}